import { GenerationPlan, ComponentNode } from '../types';
import { validateComponentProps } from '../utils/index';

/* ============================================
   GENERATOR AGENT
   ============================================ */

/**
 * Convert plan to JSX code
 */
export function generateJSX(plan: GenerationPlan): string {
  let jsx = generateFileHeader();

  jsx += '\nexport default function GeneratedComponent() {\n';
  jsx += '  return (\n';
  jsx += '    <>\n';

  // Add components
  for (const component of plan.components) {
    jsx += componentToJSX(component, 3);
  }

  jsx += '    </>\n';
  jsx += '  );\n';
  jsx += '}\n';

  return jsx;
}

/**
 * Generate file header with imports
 */
function generateFileHeader(): string {
  return `import React from 'react';
import {
  Button,
  Card,
  Header,
  Input,
  Select,
  TextArea,
  Modal,
  List,
  Grid,
  Stack,
  Alert,
  Divider,
  Text
} from '@/components/library';

/* ============================================
   AUTO-GENERATED UI COMPONENT
   ============================================
   
   Generated by AI UI Generator
   DO NOT MODIFY - Use generator to update
*/`;
}

/**
 * Convert single component to JSX
 */
function componentToJSX(component: ComponentNode, indent: number): string {
  const spaces = ' '.repeat(indent);
  const schema = validateComponentProps(component.type, component.props);

  // Check for errors
  if (schema.length > 0) {
    console.warn(`Validation warnings for ${component.type}:`, schema);
  }

  const propString = generatePropString(component.props);
  const hasChildren = component.children && component.children.length > 0;

  if (!hasChildren) {
    // Self-closing tag
    return `${spaces}<${component.type}${propString} />\n`;
  }

  // Component with children
  let jsx = `${spaces}<${component.type}${propString}>\n`;

  // Add children
  for (const child of component.children!) {
    if (typeof child === 'string') {
      jsx += `${spaces}  ${escapeJSXString(child)}\n`;
    } else {
      jsx += componentToJSX(child, indent + 2);
    }
  }

  jsx += `${spaces}</${component.type}>\n`;
  return jsx;
}

/**
 * Generate prop string from props object
 */
function generatePropString(props: Record<string, any>): string {
  if (Object.keys(props).length === 0) {
    return '';
  }

  const propsArray: string[] = [];

  for (const [key, value] of Object.entries(props)) {
    // Skip children prop
    if (key === 'children') continue;

    const propValue = generatePropValue(value);
    propsArray.push(`${key}={${propValue}}`);
  }

  return propsArray.length > 0 ? ' ' + propsArray.join(' ') : '';
}

/**
 * Generate prop value string
 */
function generatePropValue(value: any): string {
  if (typeof value === 'string') {
    return `"${value}"`;
  }

  if (typeof value === 'boolean') {
    return value.toString();
  }

  if (typeof value === 'number') {
    return value.toString();
  }

  if (Array.isArray(value)) {
    const items = value.map(v => generatePropValue(v)).join(', ');
    return `[${items}]`;
  }

  if (typeof value === 'object' && value !== null) {
    return JSON.stringify(value);
  }

  return 'undefined';
}

/**
 * Escape strings for JSX
 */
function escapeJSXString(str: string): string {
  return str.replace(/[{}]/g, '{"{"}');
}

/**
 * Apply incremental update to existing code
 */
export function applyIncrementalUpdate(
  originalCode: string,
  updatedPlan: GenerationPlan
): string {
  // For now, regenerate whole component
  // In production, would do true incremental patching
  return generateJSX(updatedPlan);
}

/**
 * Generate component preview HTML
 */
export function generatePreviewHTML(jsxCode: string): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>UI Preview</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #f5f5f5;
      padding: 20px;
    }
    
    .preview-container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      border-radius: 8px;
      padding: 24px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    
    /* Component Styles */
    [data-component="Header"] {
      margin-bottom: 24px;
      padding-bottom: 16px;
      border-bottom: 1px solid #e0e0e0;
    }
    
    [data-component="Header"] h1 {
      font-size: 32px;
      margin-bottom: 8px;
    }
    
    [data-component="Header"] p {
      color: #666;
      font-size: 14px;
    }
    
    [data-component="Card"] {
      border: 1px solid #e0e0e0;
      border-radius: 8px;
      padding: 16px;
      margin-bottom: 16px;
    }
    
    [data-component="Card"] h3 {
      margin-bottom: 12px;
      font-size: 18px;
    }
    
    [data-component="Button"] {
      display: inline-block;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-weight: 500;
      transition: all 0.2s;
    }
    
    [data-component="Button"][data-variant="primary"] {
      background: #007bff;
      color: white;
    }
    
    [data-component="Button"][data-variant="secondary"] {
      background: #6c757d;
      color: white;
    }
    
    [data-component="Button"][data-variant="danger"] {
      background: #dc3545;
      color: white;
    }
    
    [data-component="Button"]:hover {
      opacity: 0.9;
      transform: translateY(-1px);
    }
    
    [data-component="Input"],
    [data-component="Select"],
    [data-component="TextArea"] {
      display: block;
      width: 100%;
      margin-bottom: 12px;
    }
    
    [data-component="Input"] label,
    [data-component="Select"] label,
    [data-component="TextArea"] label {
      display: block;
      margin-bottom: 4px;
      font-weight: 500;
      font-size: 14px;
    }
    
    [data-component="Input"] input,
    [data-component="Select"] select,
    [data-component="TextArea"] textarea {
      width: 100%;
      padding: 8px 12px;
      border: 1px solid #ccc;
      border-radius: 4px;
      font-family: inherit;
      font-size: 14px;
    }
    
    [data-component="Stack"][data-direction="vertical"] {
      display: flex;
      flex-direction: column;
    }
    
    [data-component="Stack"][data-direction="horizontal"] {
      display: flex;
      flex-direction: row;
    }
    
    [data-component="Stack"][data-spacing="sm"] > * {
      margin-bottom: 8px;
    }
    
    [data-component="Stack"][data-spacing="md"] > * {
      margin-bottom: 16px;
    }
    
    [data-component="Stack"][data-spacing="lg"] > * {
      margin-bottom: 24px;
    }
    
    [data-component="Grid"] {
      display: grid;
      grid-template-columns: repeat(var(--columns, 1), 1fr);
      gap: var(--gap, 16px);
    }
    
    [data-component="List"] {
      list-style: none;
    }
    
    [data-component="List"] li {
      padding: 8px 0;
      border-bottom: 1px solid #eee;
    }
    
    [data-component="Alert"] {
      padding: 12px 16px;
      border-radius: 4px;
      margin-bottom: 16px;
    }
    
    [data-component="Alert"][data-type="info"] {
      background: #d1ecf1;
      color: #0c5460;
      border: 1px solid #bee5eb;
    }
    
    [data-component="Alert"][data-type="success"] {
      background: #d4edda;
      color: #155724;
      border: 1px solid #c3e6cb;
    }
    
    [data-component="Alert"][data-type="warning"] {
      background: #fff3cd;
      color: #856404;
      border: 1px solid #ffeeba;
    }
    
    [data-component="Alert"][data-type="error"] {
      background: #f8d7da;
      color: #721c24;
      border: 1px solid #f5c6cb;
    }
  </style>
</head>
<body>
  <div class="preview-container">
    <p style="color: #999; margin-bottom: 20px; font-size: 12px;">
      Preview (Sandboxed)
    </p>
    <!-- Generated UI will be inserted here -->
    <!-- This is a static preview - interactivity requires full React runtime -->
  </div>
</body>
</html>`;
}

/**
 * Extract metadata from generated code
 */
export function extractMetadata(code: string): {
  componentCount: number;
  linesOfCode: number;
  components: string[];
} {
  const lines = code.split('\n').filter(line => line.trim().length > 0);
  const componentMatches = code.match(/<(\w+)/g) || [];
  const uniqueComponents = new Set(
    componentMatches.map(match => match.replace('<', '')).filter(c => !isHTMLTag(c))
  );

  return {
    componentCount: uniqueComponents.size,
    linesOfCode: lines.length,
    components: Array.from(uniqueComponents)
  };
}

/**
 * Check if tag is HTML tag
 */
function isHTMLTag(tag: string): boolean {
  const htmlTags = [
    'html', 'head', 'body', 'div', 'span', 'p', 'a', 'button',
    'input', 'form', 'label', 'h1', 'h2', 'h3', 'ul', 'ol', 'li'
  ];
  return htmlTags.includes(tag.toLowerCase());
}
